options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Step 1: Authenticate with Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo $PROJECT_ID
        gcloud auth configure-docker ${_REGION}-docker.pkg.dev

  # sonar scanner cli
  - name: 'sonarsource/sonar-scanner-cli'
    entrypoint: 'bash'
    secretEnv: ['SONAR_TOKEN_TEST']
    args:
      - '-c'
      - |
        mkdir -P /tmp/.sonar
        mkdir -P /tmp/.scannerwork
        export SONAR_USER_HOME=/tmp/.sonar
        sonar-scanner \
         -Dsonar.projectKey=vlc-sonar-1m-cloudbuild \
         -Dsonar.projectName=vlc-sonar-1m-cloudbuild \
         -Dsonar.sources=. \
         -Dsonar.host.url=https://sonar-demo-pt.iexperts.cloud/ \
         -Dsonar.login=sqp_8011d7ed31ea61bf40db20509b79b3b245b61ead \
         -Dsonar.working.directory=/tmp/.scannerwork

