# Top‐level timeout set to 14400 seconds (4 hours)
timeout: "14400s"

options:
  logging: CLOUD_LOGGING_ONLY

  # Pick a larger machine type than the default.
  # Available built‐in options: E2_SMALL, E2_MEDIUM (default), E2_HIGHCPU_8, E2_HIGHCPU_32
  machineType: "E2_HIGHCPU_8"

steps:
  - name: 'sonarsource/sonar-scanner-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p /tmp/.sonar
        mkdir -p /tmp/.scannerwork
        export SONAR_USER_HOME=/tmp/.sonar
        sonar-scanner \
          -Dsonar.projectKey=poc-1million-line-of-code \
          -Dsonar.projectName=poc-1million-line-of-code \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonar.iexperts.cloud \
          -Dsonar.login=sqp_dec82ec53c9764fffbed4df1f4fc6c9d62a9ef99 \
          -Dsonar.working.directory=/tmp/.scannerwork


