# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Install common tools (curl, unzip, build essentials)
  # Using a standard Ubuntu image for building C/C++ projects
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y curl unzip build-essential git 
        # 'build-essential' provides gcc, g++, make etc. Adjust based on your project's build dependencies (e.g., autotools, cmake)
